# fly.toml app configuration file generated for dating-bulgaria on 2023-06-28T11:45:59+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "dating-bulgaria"
primary_region = "ams"

[build]
  image = "offeckk/datingapp:latest"

[env]
  ASPNETCORE_URLS="http://+:8080"
  CloudinarySettings__CloudName="dfk8grfa3"
  CloudinarySettings__ApiKey="587938959247557"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
